package org.hotel.entity;

// default package
// Generated Aug 9, 2017 9:25:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MCity generated by hbm2java
 */
@Entity
@Table(name = "m_city", catalog = "hotels")
public class MCity implements java.io.Serializable {

	private Integer ctyId;
	private RDistrict RDistrict;
	private String ctyName;
	private String ctyActive;
	private Set<MHotels> MHotelses = new HashSet<MHotels>(0);

	public MCity() {
	}

	public MCity(RDistrict RDistrict, String ctyName, String ctyActive) {
		this.RDistrict = RDistrict;
		this.ctyName = ctyName;
		this.ctyActive = ctyActive;
	}

	public MCity(RDistrict RDistrict, String ctyName, String ctyActive, Set<MHotels> MHotelses) {
		this.RDistrict = RDistrict;
		this.ctyName = ctyName;
		this.ctyActive = ctyActive;
		this.MHotelses = MHotelses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cty_id", unique = true, nullable = false)
	public Integer getCtyId() {
		return this.ctyId;
	}

	public void setCtyId(Integer ctyId) {
		this.ctyId = ctyId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "dtr_id", nullable = false)
	public RDistrict getRDistrict() {
		return this.RDistrict;
	}

	public void setRDistrict(RDistrict RDistrict) {
		this.RDistrict = RDistrict;
	}

	@Column(name = "cty_name", nullable = false, length = 50)
	public String getCtyName() {
		return this.ctyName;
	}

	public void setCtyName(String ctyName) {
		this.ctyName = ctyName;
	}

	@Column(name = "cty_active", nullable = false, length = 2)
	public String getCtyActive() {
		return this.ctyActive;
	}

	public void setCtyActive(String ctyActive) {
		this.ctyActive = ctyActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MCity")
	public Set<MHotels> getMHotelses() {
		return this.MHotelses;
	}

	public void setMHotelses(Set<MHotels> MHotelses) {
		this.MHotelses = MHotelses;
	}

}
