package org.hotel.entity;

// default package
// Generated Aug 9, 2017 9:25:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RDistrict generated by hbm2java
 */
@Entity
@Table(name = "r_district", catalog = "hotels")
public class RDistrict implements java.io.Serializable {

	private Integer dtrId;
	private String dtrName;
	private String dtrActive;
	private Set<MCity> MCities = new HashSet<MCity>(0);

	public RDistrict() {
	}

	public RDistrict(String dtrName, String dtrActive) {
		this.dtrName = dtrName;
		this.dtrActive = dtrActive;
	}

	public RDistrict(String dtrName, String dtrActive, Set<MCity> MCities) {
		this.dtrName = dtrName;
		this.dtrActive = dtrActive;
		this.MCities = MCities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dtr_id", unique = true, nullable = false)
	public Integer getDtrId() {
		return this.dtrId;
	}

	public void setDtrId(Integer dtrId) {
		this.dtrId = dtrId;
	}

	@Column(name = "dtr_name", nullable = false, length = 50)
	public String getDtrName() {
		return this.dtrName;
	}

	public void setDtrName(String dtrName) {
		this.dtrName = dtrName;
	}

	@Column(name = "dtr_active", nullable = false, length = 2)
	public String getDtrActive() {
		return this.dtrActive;
	}

	public void setDtrActive(String dtrActive) {
		this.dtrActive = dtrActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RDistrict")
	public Set<MCity> getMCities() {
		return this.MCities;
	}

	public void setMCities(Set<MCity> MCities) {
		this.MCities = MCities;
	}

}
